### ISSUE TITLE
Suggestion: Change the leaderboard command

### ISSUE THREAD

**Issue by eternalmoon1234** [Milo123459/Spencer#100]
Maybe for the leaderboard command we should show the top users for each guild rather than for every guild?

**Comment by Milo123459** [comment]
Well the economy is global so, idk.

**Comment by eternalmoon1234** [comment]
ok

**Comment by Milo123459** [comment]
Most likely not, sorry.
If you'd like you can make a PR for example:
sp!leaderboard - displays global
sp!leaderboard guild - displays richest users in this guild

If you want, if not I'll close this issue

**Comment by eternalmoon1234** [comment]
ok
