### ISSUE TITLE
Implement changing statuses

### ISSUE THREAD

**Issue by ArezeFN** [Milo123459/Spencer#155]
Hi, using easy code you could make it so the bot iterates through an array of statuses this would like something like this:

var arrOfStatuses = ["Chilling on the beach", "Having fun", "sp!help for all commands"] // etc. .
var index = 0
client.on("ready", () => {
setInterval(() => {
client.user.setActivity(arrOfStatuses[i])
if(index === arrOfStatuses.length - 1){
i = 0
} else i++

}, 60000) // any time interval this is just an example
}

**Comment by Milo123459** [comment]
We'll consider it, thanks for suggesting!
