### ISSUE TITLE
Code Blocker

### ISSUE THREAD

**Issue by ghost** [Milo123459/Spencer#159]
Heres how:
``
client.on("message", (msg) => {
if(msg.channel.id === theChannelIdNotAllowed){
if(!(msg.content.length.length - msg.content.split("\`\`\`").join("").length) >= 6) return;
msg.reply("You cannot send code in this channel")
// any other precautions to penalise the user

}

})

``

**Comment by ArezeFN** [comment]
it shouldn't be .length.length

**Comment by ArezeFN** [comment]
i meant .length
