### ISSUE TITLE
Cannot read property 'members' of undefined

### ISSUE THREAD

**Issue by hanatic** [Milo123459/Spencer#231]
I'm trying to run Spencer locally and keep getting a TypeError: 
```
(node:13784) UnhandledPromiseRejectionWarning: TypeError: Cannot read property 'members' of undefined
    at UtilsManager.checkMultipleRoles (C:\Users\isaac\OneDrive\Documents\GitHub\Spencer\src\utils\Utils.ts:69:13)
    at run (C:\Users\isaac\OneDrive\Documents\GitHub\Spencer\src\events\Guild Events\MessageEvent.ts:248:17)
    at processTicksAndRejections (internal/process/task_queues.js:95:5)
```

It seems to be an error being thrown in Utils.ts in the checkMultipleRoles method: in line 95 (:
```ts
	public checkMultipleRoles(
               // ...
	): boolean {	  
  	/* this bit here -> */ const member: GuildMember = this.client.guilds.cache
			.get(guild)
			.members.cache.get(user);
		if (!member) return false;
		const res: boolean[] = [];
		if (typeof roles == 'string') {
			res.push(member.roles.cache.has(roles));
		} else {
			roles.map((value: string) => {
				res.push(member.roles.cache.has(value));
			});
		}
		return !!res.filter((value: boolean) => !!value).length;
	}
```

I'm not an expert with TypeScript so I can't suggest a fix, but it looks like you need to define Spencer().guilds in client/Client.ts because it's returning undefined. I'm not sure why this is though because Spencer() extends Discord.Client() which has a .guilds property.

**Comment by Milo123459** [comment]
Hey,
That's hardcoded for development, allowing me to check if someone has donated/has premium. I'm going to remove it.

**Comment by Milo123459** [comment]
Alright, fixed, please update your master branch you are working on. Click the fetch upstream button on your fork.
Thanks!
