### ISSUE TITLE
[Suggestion]: Add Backup System

### ISSUE THREAD

**Issue by Beatzoid** [Milo123459/Spencer#45]
Add a server backup and server restore function to the bot. Examples:
`?backup` - Backups all data of server (channels, roles, permissions, etc) to some location and returns the backup id
`?restore <id>` restores all data from the id and overwrites current guild data

**Comment by Milo123459** [comment]
Cool idea, since Spencer is a private bot, do you think this is a good idea for a private bot?
@Beatzoid

**Comment by Beatzoid** [comment]
Oh I thought it was a public bot. It could be useful for your support/community server incase an admin abuses/gets hacked, but I'm not sure

**Comment by Milo123459** [comment]
Hmm, I'll leave it open for people to vote on whether they like it or not.

**Comment by Milo123459** [comment]
/polls 'Add backup & restore system' "Don't add backup & restore system"

**Comment by Beatzoid** [comment]
> Hmm, I'll leave it open for people to vote on whether they like it or not.

Ok sounds good!

**Comment by Milo123459** [comment]
At second thought, I'm going to close this, it'd just be a hassle in my opinion, feel free to reopen it.
