### ISSUE TITLE
Discord.js DB

### ISSUE THREAD

**Issue by Khaogamermain01** [Milo123459/Spencer#87]
Where is The DB tutorial I can’t find it anywhereIf you have a video please show me because I don’t know what to do with this DB thing I am stuck on here for days now please help! Thanks 

This is for the tutorial bot

**Comment by Milo123459** [comment]
This is not the correct repo to report this.

**Comment by Khaogamermain01** [comment]
@Milo123459 You can’t put an issue in the tutorial repo

**Comment by Milo123459** [comment]
I know, because I discontinued the series. Please stop.
